AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**'
Metrics/LineLength:
  Max: 120

# Disables "Use nested module/class definitions instead of compact style" warning
ClassAndModuleChildren:
  Enabled: false

# Disables "Missing top-level class documentation comment" warning
Documentation:
  Enabled: false
